baseURL = "https://theden.github.io/" #https://thoughts.theden.sh/"
languageCode = "en-us"
title = "thoughts.theden.sh"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
canonifyurls = true


[params]
  dark = "on"
  highlight = true
  description = "thoughts.theden.sh — Denis Khoshaba"
  author = "Denis Khoshba"
  GithubID = "TheDen"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
